server:
  port: 8082
  servlet:
    context-path: /clinic

spring:
  application:
    name: clinic_admin_api

  # Configuracao do banco de dados PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator