server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /clinic

spring:
  application:
    name: clinic_admin_api

  # Configuracao do banco de dados PostgreSQL
  # Utiliza variaveis de ambiente ou valores padrao para desenvolvimento
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:clinic_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuracao do Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.nfdtech.clinic_admin_api.controllers
  model-and-view-allowed: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator

# Logging
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG